//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 
namespace SchedulesDirect {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Net;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="xtvdBinding", Namespace="urn:TMSWebServices")]
    public partial class xtvdWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback downloadOperationCompleted;
        
        private System.Threading.SendOrPostCallback acknowledgeOperationCompleted;
        
        /// <remarks/>
        public xtvdWebService() {
            this.Url = "http://webservices.schedulesdirect.tmsdatadirect.com/schedulesdirect/tvlistings/x" +
                "tvdService";
        }

        protected override System.Net.WebRequest GetWebRequest(Uri uri)
        {
            System.Net.WebRequest request = base.GetWebRequest(uri);
            if (this.EnableDecompression)
            {
                request.Headers.Add("Accept-Encoding", "gzip");
            }
            return request;
        }
        
        /// <remarks/>
        public event downloadCompletedEventHandler downloadCompleted;
        
        /// <remarks/>
        public event acknowledgeCompletedEventHandler acknowledgeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:TMSWebServices:xtvdWebService#download", RequestNamespace="urn:TMSWebServices", ResponseNamespace="urn:TMSWebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("xtvdResponse")]
        public xtvdResponse download(string startTime, string endTime) {
            object[] results = this.Invoke("download", new object[] {
                        startTime,
                        endTime});
            return ((xtvdResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begindownload(string startTime, string endTime, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("download", new object[] {
                        startTime,
                        endTime}, callback, asyncState);
        }
        
        /// <remarks/>
        public xtvdResponse Enddownload(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((xtvdResponse)(results[0]));
        }
        
        /// <remarks/>
        public void downloadAsync(string startTime, string endTime) {
            this.downloadAsync(startTime, endTime, null);
        }
        
        /// <remarks/>
        public void downloadAsync(string startTime, string endTime, object userState) {
            if ((this.downloadOperationCompleted == null)) {
                this.downloadOperationCompleted = new System.Threading.SendOrPostCallback(this.OndownloadOperationCompleted);
            }
            this.InvokeAsync("download", new object[] {
                        startTime,
                        endTime}, this.downloadOperationCompleted, userState);
        }
        
        private void OndownloadOperationCompleted(object arg) {
            if ((this.downloadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.downloadCompleted(this, new downloadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:#acknowledge", RequestNamespace="urn:TMSWebServices", ResponseNamespace="urn:TMSWebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("downloadTimes")]
        public downloadTimes acknowledge() {
            object[] results = this.Invoke("acknowledge", new object[0]);
            return ((downloadTimes)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginacknowledge(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("acknowledge", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public downloadTimes Endacknowledge(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((downloadTimes)(results[0]));
        }
        
        /// <remarks/>
        public void acknowledgeAsync() {
            this.acknowledgeAsync(null);
        }
        
        /// <remarks/>
        public void acknowledgeAsync(object userState) {
            if ((this.acknowledgeOperationCompleted == null)) {
                this.acknowledgeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnacknowledgeOperationCompleted);
            }
            this.InvokeAsync("acknowledge", new object[0], this.acknowledgeOperationCompleted, userState);
        }
        
        private void OnacknowledgeOperationCompleted(object arg) {
            if ((this.acknowledgeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.acknowledgeCompleted(this, new acknowledgeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:TMSWebServices")]
    public partial class xtvdResponse {
        
        private string[] messagesField;
        
        private xtvd xtvdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("message", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
            }
        }
        
        /// <remarks/>
        public xtvd xtvd {
            get {
                return this.xtvdField;
            }
            set {
                this.xtvdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:TMSWebServices")]
    public partial class xtvd {
        
        private stationsStation[] stationsField;
        
        private lineupsLineup[] lineupsField;
        
        private schedulesSchedule[] schedulesField;
        
        private programsProgram[] programsField;
        
        private productionCrewCrew[] productionCrewField;
        
        private genresProgramGenre[] genresField;
        
        private System.DateTime fromField;
        
        private System.DateTime toField;
        
        private float schemaVersionField;
        
        public xtvd() {
            this.schemaVersionField = ((float)(1.3F));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("station", IsNullable=false)]
        public stationsStation[] stations {
            get {
                return this.stationsField;
            }
            set {
                this.stationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("lineup", IsNullable=false)]
        public lineupsLineup[] lineups {
            get {
                return this.lineupsField;
            }
            set {
                this.lineupsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("schedule", IsNullable=false)]
        public schedulesSchedule[] schedules {
            get {
                return this.schedulesField;
            }
            set {
                this.schedulesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("program", IsNullable=false)]
        public programsProgram[] programs {
            get {
                return this.programsField;
            }
            set {
                this.programsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("crew", IsNullable=false)]
        public productionCrewCrew[] productionCrew {
            get {
                return this.productionCrewField;
            }
            set {
                this.productionCrewField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("programGenre", IsNullable=false)]
        public genresProgramGenre[] genres {
            get {
                return this.genresField;
            }
            set {
                this.genresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime from {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime to {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float schemaVersion {
            get {
                return this.schemaVersionField;
            }
            set {
                this.schemaVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:TMSWebServices")]
    public partial class stationsStation {
        
        private string callSignField;
        
        private string nameField;
        
        private string fccChannelNumberField;
        
        private string affiliateField;
        
        private int idField;
        
        /// <remarks/>
        public string callSign {
            get {
                return this.callSignField;
            }
            set {
                this.callSignField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string fccChannelNumber {
            get {
                return this.fccChannelNumberField;
            }
            set {
                this.fccChannelNumberField = value;
            }
        }
        
        /// <remarks/>
        public string affiliate {
            get {
                return this.affiliateField;
            }
            set {
                this.affiliateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:TMSWebServices")]
    public partial class downloadTimes {
        
        private System.DateTime blockedDownloadTimeField;
        
        private bool blockedDownloadTimeFieldSpecified;
        
        private System.DateTime suggestedDownloadTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime blockedDownloadTime {
            get {
                return this.blockedDownloadTimeField;
            }
            set {
                this.blockedDownloadTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool blockedDownloadTimeSpecified {
            get {
                return this.blockedDownloadTimeFieldSpecified;
            }
            set {
                this.blockedDownloadTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime suggestedDownloadTime {
            get {
                return this.suggestedDownloadTimeField;
            }
            set {
                this.suggestedDownloadTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:TMSWebServices")]
    public partial class crewMember {
        
        private string roleField;
        
        private string givennameField;
        
        private string surnameField;
        
        /// <remarks/>
        public string role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string givenname {
            get {
                return this.givennameField;
            }
            set {
                this.givennameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:TMSWebServices")]
    public partial class lineupsLineup {
        
        private lineupsLineupMap[] mapField;
        
        private string idField;
        
        private string nameField;
        
        private string userLineupNameField;
        
        private string locationField;
        
        private lineupTypes typeField;
        
        private string deviceField;
        
        private string postalCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("map")]
        public lineupsLineupMap[] map {
            get {
                return this.mapField;
            }
            set {
                this.mapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string userLineupName {
            get {
                return this.userLineupNameField;
            }
            set {
                this.userLineupNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public lineupTypes type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string device {
            get {
                return this.deviceField;
            }
            set {
                this.deviceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string postalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:TMSWebServices")]
    public partial class lineupsLineupMap {
        
        private lineupsLineupMapOnAir[] onAirField;
        
        private int stationField;
        
        private string channelField;
        
        private string channelMinorField;
        
        private System.DateTime fromField;
        
        private bool fromFieldSpecified;
        
        private System.DateTime toField;
        
        private bool toFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("onAir")]
        public lineupsLineupMapOnAir[] onAir {
            get {
                return this.onAirField;
            }
            set {
                this.onAirField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int station {
            get {
                return this.stationField;
            }
            set {
                this.stationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string channel {
            get {
                return this.channelField;
            }
            set {
                this.channelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string channelMinor {
            get {
                return this.channelMinorField;
            }
            set {
                this.channelMinorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime from {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fromSpecified {
            get {
                return this.fromFieldSpecified;
            }
            set {
                this.fromFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime to {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool toSpecified {
            get {
                return this.toFieldSpecified;
            }
            set {
                this.toFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:TMSWebServices")]
    public partial class lineupsLineupMapOnAir {
        
        private System.DateTime fromField;
        
        private System.DateTime toField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="time")]
        public System.DateTime from {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="time")]
        public System.DateTime to {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:TMSWebServices")]
    public enum lineupTypes {
        
        /// <remarks/>
        Cable,
        
        /// <remarks/>
        CableDigital,
        
        /// <remarks/>
        Satellite,
        
        /// <remarks/>
        LocalBroadcast,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:TMSWebServices")]
    public partial class schedulesSchedule {
        
        private schedulesSchedulePart partField;
        
        private string programField;
        
        private int stationField;
        
        private System.DateTime timeField;
        
        private string durationField;
        
        private bool repeatField;
        
        private bool repeatFieldSpecified;
        
        private tvRatings tvRatingField;
        
        private bool tvRatingFieldSpecified;
        
        private bool stereoField;
        
        private bool stereoFieldSpecified;
        
        private bool subtitledField;
        
        private bool subtitledFieldSpecified;
        
        private bool hdtvField;
        
        private bool hdtvFieldSpecified;
        
        private bool closeCaptionedField;
        
        private bool closeCaptionedFieldSpecified;
        
        private schedulesScheduleDolby dolbyField;
        
        private bool dolbyFieldSpecified;
        
        private bool newField;
        
        private bool newFieldSpecified;
        
        private bool eiField;
        
        private bool eiFieldSpecified;
        
        /// <remarks/>
        public schedulesSchedulePart part {
            get {
                return this.partField;
            }
            set {
                this.partField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string program {
            get {
                return this.programField;
            }
            set {
                this.programField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int station {
            get {
                return this.stationField;
            }
            set {
                this.stationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="duration")]
        public string duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool repeat {
            get {
                return this.repeatField;
            }
            set {
                this.repeatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool repeatSpecified {
            get {
                return this.repeatFieldSpecified;
            }
            set {
                this.repeatFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public tvRatings tvRating {
            get {
                return this.tvRatingField;
            }
            set {
                this.tvRatingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tvRatingSpecified {
            get {
                return this.tvRatingFieldSpecified;
            }
            set {
                this.tvRatingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool stereo {
            get {
                return this.stereoField;
            }
            set {
                this.stereoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stereoSpecified {
            get {
                return this.stereoFieldSpecified;
            }
            set {
                this.stereoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool subtitled {
            get {
                return this.subtitledField;
            }
            set {
                this.subtitledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool subtitledSpecified {
            get {
                return this.subtitledFieldSpecified;
            }
            set {
                this.subtitledFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool hdtv {
            get {
                return this.hdtvField;
            }
            set {
                this.hdtvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hdtvSpecified {
            get {
                return this.hdtvFieldSpecified;
            }
            set {
                this.hdtvFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool closeCaptioned {
            get {
                return this.closeCaptionedField;
            }
            set {
                this.closeCaptionedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool closeCaptionedSpecified {
            get {
                return this.closeCaptionedFieldSpecified;
            }
            set {
                this.closeCaptionedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public schedulesScheduleDolby dolby {
            get {
                return this.dolbyField;
            }
            set {
                this.dolbyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dolbySpecified {
            get {
                return this.dolbyFieldSpecified;
            }
            set {
                this.dolbyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool @new {
            get {
                return this.newField;
            }
            set {
                this.newField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool newSpecified {
            get {
                return this.newFieldSpecified;
            }
            set {
                this.newFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool ei {
            get {
                return this.eiField;
            }
            set {
                this.eiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eiSpecified {
            get {
                return this.eiFieldSpecified;
            }
            set {
                this.eiFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:TMSWebServices")]
    public partial class schedulesSchedulePart {
        
        private uint numberField;
        
        private uint totalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:TMSWebServices")]
    public enum tvRatings {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("TV-Y")]
        TVY,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("TV-Y7")]
        TVY7,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("TV-G")]
        TVG,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("TV-PG")]
        TVPG,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("TV-14")]
        TV14,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("TV-MA")]
        TVMA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:TMSWebServices")]
    public enum schedulesScheduleDolby {
        
        /// <remarks/>
        Dolby,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Dolby Digital")]
        DolbyDigital,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:TMSWebServices")]
    public partial class programsProgram {
        
        private string titleField;
        
        private string subtitleField;
        
        private string descriptionField;
        
        private mpaaRatings mpaaRatingField;
        
        private bool mpaaRatingFieldSpecified;
        
        private starRating starRatingField;
        
        private bool starRatingFieldSpecified;
        
        private string runTimeField;
        
        private string yearField;
        
        private string showTypeField;
        
        private string seriesField;
        
        private tvColorCode colorCodeField;
        
        private bool colorCodeFieldSpecified;
        
        private movieAdvisories[] advisoriesField;
        
        private string syndicatedEpisodeNumberField;
        
        private System.DateTime originalAirDateField;
        
        private bool originalAirDateFieldSpecified;
        
        private string idField;
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string subtitle {
            get {
                return this.subtitleField;
            }
            set {
                this.subtitleField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public mpaaRatings mpaaRating {
            get {
                return this.mpaaRatingField;
            }
            set {
                this.mpaaRatingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mpaaRatingSpecified {
            get {
                return this.mpaaRatingFieldSpecified;
            }
            set {
                this.mpaaRatingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public starRating starRating {
            get {
                return this.starRatingField;
            }
            set {
                this.starRatingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool starRatingSpecified {
            get {
                return this.starRatingFieldSpecified;
            }
            set {
                this.starRatingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="duration")]
        public string runTime {
            get {
                return this.runTimeField;
            }
            set {
                this.runTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="gYear")]
        public string year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        public string showType {
            get {
                return this.showTypeField;
            }
            set {
                this.showTypeField = value;
            }
        }
        
        /// <remarks/>
        public string series {
            get {
                return this.seriesField;
            }
            set {
                this.seriesField = value;
            }
        }
        
        /// <remarks/>
        public tvColorCode colorCode {
            get {
                return this.colorCodeField;
            }
            set {
                this.colorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool colorCodeSpecified {
            get {
                return this.colorCodeFieldSpecified;
            }
            set {
                this.colorCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("advisory", IsNullable=false)]
        public movieAdvisories[] advisories {
            get {
                return this.advisoriesField;
            }
            set {
                this.advisoriesField = value;
            }
        }
        
        /// <remarks/>
        public string syndicatedEpisodeNumber {
            get {
                return this.syndicatedEpisodeNumberField;
            }
            set {
                this.syndicatedEpisodeNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime originalAirDate {
            get {
                return this.originalAirDateField;
            }
            set {
                this.originalAirDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool originalAirDateSpecified {
            get {
                return this.originalAirDateFieldSpecified;
            }
            set {
                this.originalAirDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:TMSWebServices")]
    public enum mpaaRatings {
        
        /// <remarks/>
        Adult,
        
        /// <remarks/>
        AO,
        
        /// <remarks/>
        G,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("NC-17")]
        NC17,
        
        /// <remarks/>
        NONE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("NOT RATED")]
        NOTRATED,
        
        /// <remarks/>
        NR,
        
        /// <remarks/>
        PG,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("PG-13")]
        PG13,
        
        /// <remarks/>
        R,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:TMSWebServices")]
    public enum starRating {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("*")]
        Item,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("*+")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("**")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("**+")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("***")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("***+")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("****")]
        Item6,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:TMSWebServices")]
    public enum tvColorCode {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("B & W")]
        BW,
        
        /// <remarks/>
        Color,
        
        /// <remarks/>
        Colorized,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Color and B & W")]
        ColorandBW,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:TMSWebServices")]
    public enum movieAdvisories {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Adult Situations")]
        AdultSituations,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Adolescentes y Adultos")]
        AdolescentesyAdultos,
        
        /// <remarks/>
        Adultos,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Brief Nudity")]
        BriefNudity,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Graphic Language")]
        GraphicLanguage,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Graphic Violence")]
        GraphicViolence,
        
        /// <remarks/>
        Language,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Mild Violence")]
        MildViolence,
        
        /// <remarks/>
        Nudity,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Publico General")]
        PublicoGeneral,
        
        /// <remarks/>
        Rape,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Strong Sexual Content")]
        StrongSexualContent,
        
        /// <remarks/>
        Violence,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:TMSWebServices")]
    public partial class productionCrewCrew {
        
        private crewMember[] memberField;
        
        private string programField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("member")]
        public crewMember[] member {
            get {
                return this.memberField;
            }
            set {
                this.memberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string program {
            get {
                return this.programField;
            }
            set {
                this.programField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:TMSWebServices")]
    public partial class genresProgramGenre {
        
        private genresProgramGenreGenre[] genreField;
        
        private string programField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("genre")]
        public genresProgramGenreGenre[] genre {
            get {
                return this.genreField;
            }
            set {
                this.genreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string program {
            get {
                return this.programField;
            }
            set {
                this.programField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:TMSWebServices")]
    public partial class genresProgramGenreGenre {
        
        private string classField;
        
        private int relevanceField;
        
        /// <remarks/>
        public string @class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
            }
        }
        
        /// <remarks/>
        public int relevance {
            get {
                return this.relevanceField;
            }
            set {
                this.relevanceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void downloadCompletedEventHandler(object sender, downloadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class downloadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal downloadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public xtvdResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((xtvdResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void acknowledgeCompletedEventHandler(object sender, acknowledgeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class acknowledgeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal acknowledgeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public downloadTimes Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((downloadTimes)(this.results[0]));
            }
        }
    }
}
